openapi: 3.1.0
info:
  title: Mi API
  version: 1.0.0
paths:
  /posts:
    get:
      summary: Obtiene todos los posts
      responses:
        '200':
          description: Respuesta exitosa
    parameters: [] #evitar errores
  /posts/{postId}:
    get:
      summary: Obtiene un post por su ID
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Respuesta exitosa
